version: '3.8'

services:
  redis:
    image: 'redis:7-alpine'
    container_name: 'voxly-redis'
    
    command: redis-server --requirepass osf2DTzMWmDHZSaQ
    
    ports:
      - '127.0.0.1:6379:6379'
      
    volumes:
      - 'redis-data:/data'
      
volumes:
  redis-data:
