name: Flutter Web CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      - name: Pub get
        run: flutter pub get
        working-directory: ./voxly_frontend

      - name: Build web
        run: flutter build web --release
        working-directory: ./voxly_frontend

      # Очистка папки сайта на сервере
      - name: Clean folder on VPS
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/voxly_frontend/*
            mkdir -p /var/www/voxly_frontend

      # Копирование файлов сборки в корень сайта
      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "voxly_frontend/build/web/*"
          target: "/var/www/voxly_frontend/"
