name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Проверка кода (Checkout)
        uses: actions/checkout@v4
        # ВАЖНО: При checkout вся структура репозитория скачивается в папку runner'а.

      - name: 2. Настройка Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: 3. Получение зависимостей (Фронтенд)
        run: flutter pub get
        working-directory: ./voxly_frontend

      - name: 4. Сборка Flutter Web
        run: flutter build web --release
        working-directory: ./voxly_frontend
          
      # --- ШАГ 5: ПУБЛИКАЦИЯ В ВЕТКУ GH-PAGES (Фронтенд) ---
      - name: 5. Публикация веб-сборки в ветку gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./voxly_frontend/build/web 
          publish_branch: gh-pages
          commit_message: "Deploying Flutter Web build via CI/CD"
          
      # --- ШАГ 6: РАЗВЕРТЫВАНИЕ НА VPS SELECTEL (Фронтенд + Бэкенд) ---
      - name: 6. Развертывание на VPS Selectel (Фронтенд и Бэкенд)
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Команда, которая выполняется на вашем VPS
          script: |
            # =========================================================
            # ЧАСТЬ 1: Развертывание ФРОНТЕНДА (Скачивание из gh-pages)
            # =========================================================
            
            REPO_NAME="${{ github.repository }}"
            DEPLOY_TARGET_FRONTEND="/var/www/voxly_frontend" # Целевая папка для фронтенда
            TEMP_ARCHIVE="/tmp/gh-pages-build.zip"
            TEMP_DIR="/tmp/gh-pages-content"
            DOWNLOAD_URL="https://api.github.com/repos/$REPO_NAME/zipball/gh-pages"

            echo "Скачивание и развертывание ФРОНТЕНДА..."

            # 1. Скачиваем ZIP-архив ветки gh-pages
            wget -q -O "$TEMP_ARCHIVE" "$DOWNLOAD_URL"
            
            # 2. Распаковываем архив во временную папку
            mkdir -p "$TEMP_DIR"
            unzip -q -o "$TEMP_ARCHIVE" -d "$TEMP_DIR"
            
            # 3. Находим корневую папку с файлами внутри архива (имеет случайное имя)
            BUILD_FOLDER=$(find "$TEMP_DIR" -mindepth 1 -maxdepth 1 -type d | head -n 1)
            
            # 4. Очищаем целевую папку фронтенда
            mkdir -p "$DEPLOY_TARGET_FRONTEND"
            find "$DEPLOY_TARGET_FRONTEND" -mindepth 1 -delete
            
            # 5. Копируем файлы фронтенда
            cp -r "$BUILD_FOLDER"/* "$DEPLOY_TARGET_FRONTEND"/

            # 6. Уборка
            rm -rf "$TEMP_DIR" "$TEMP_ARCHIVE"

            # 7. Перезапускаем HTTP-сервер фронтенда
            echo "Перезапуск voxly-frontend..."
            pm2 reload voxly-frontend || pm2 start http-server --name "voxly-frontend" -- "$DEPLOY_TARGET_FRONTEND" -p 8080
            
            # =========================================================
            # ЧАСТЬ 2: Развертывание БЭКЕНДА (Обновление из главного репо)
            # =========================================================
            
            BACKEND_TARGET_DIR="/root/voxly-backend" # Целевая папка на VPS
            
            echo "Развертывание БЭКЕНДА в $BACKEND_TARGET_DIR..."

            # Проверка наличия git
            if ! command -v git &> /dev/null; then
              echo "ОШИБКА: Команда 'git' не найдена на VPS. Пожалуйста, установите git."
              exit 1 # Завершаемся, если git не установлен
            fi

            REPO_URL="https://github.com/${{ github.repository }}.git"
            
            # 8. Создаем целевую папку и переходим в нее
            mkdir -p "$BACKEND_TARGET_DIR"
            cd "$BACKEND_TARGET_DIR" || { echo "ОШИБКА: Не удалось перейти в $BACKEND_TARGET_DIR. Проверьте права."; exit 1; }

            # 9. Инициализация/Настройка Git
            if [ ! -d ".git" ]; then
              # Если это первое развертывание (или в папке нет .git):
              echo "Инициализация Git репозитория..."
              git init --initial-branch=main || { echo "ОШИБКА: Не удалось инициализировать git."; exit 1; }
              git remote add origin "$REPO_URL" || { echo "ОШИБКА: Не удалось добавить remote origin."; exit 1; }
            fi
            
            # 10. Обновление: принудительно получаем файлы и сбрасываем локальные изменения
            echo "Обновление файлов бэкенда через Git Pull..."
            
            # 10.1. Получаем свежие данные с сервера
            git fetch origin main || { echo "ОШИБКА: Не удалось выполнить git fetch."; exit 1; }
            
            # 10.2. Сбрасываем изменения (включая удаление файлов, которых больше нет)
            # Эта команда гарантирует, что локальная папка полностью совпадает с веткой main
            git reset --hard origin/main || { echo "ОШИБКА: Не удалось выполнить git reset."; exit 1; }

            # 11. Установка зависимостей Node.js (происходит внутри $BACKEND_TARGET_DIR)
            echo "Установка зависимостей Node.js..."
            npm install || { echo "ОШИБКА: Не удалось выполнить npm install."; exit 1; }
            
            # 12. Перезапускаем PM2-процесс бэкенда
            echo "Перезапуск voxly-backend..."
            pm2 reload voxly-backend || { echo "ОШИБКА: Не удалось перезапустить PM2 процесс 'voxly-backend'."; }
            
            # 13. Сохраняем состояние PM2
            echo "Сохранение состояния PM2..."
            pm2 save
