name: Backend CI/CD (Только бэкенд)

on:
  push:
    branches:
      - main
    paths:
      - 'voxly_backend/**'
      - '.github/workflows/deploy_backend_only.yml'

  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Проверка кода (Checkout)
        uses: actions/checkout@v4

      - name: 2. Копирование файлов БЭКЕНДА на VPS (/root/voxly-backend)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./voxly_backend/*"
          target: "/root/voxly-backend"
          overwrite: true
          
      - name: 3. Установка зависимостей и перезапуск на VPS
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            BACKEND_TARGET_DIR="/root/voxly-backend"
            
            echo "Развертывание БЭКЕНДА в $BACKEND_TARGET_DIR..."
            
            echo "Аварийная очистка вложенных папок..."
            rm -rf "$BACKEND_TARGET_DIR/voxly_backend"
            rm -rf "$BACKEND_TARGET_DIR/voxly_frontend"
            
            cd "$BACKEND_TARGET_DIR" || { echo "ОШИБКА: Не удалось перейти в $BACKEND_TARGET_DIR. Проверьте путь и права."; exit 1; }

            echo "Установка зависимостей Node.js..."
            npm install
            
            echo "Перезапуск voxly-backend с ENV..."
            
            ENV_ARGS="--env PORT=${{ secrets.PORT }} \
              --env REDIS_URL=${{ secrets.REDIS_URL }} \
              --env OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
              --env LIVEKIT_URL=${{ secrets.LIVEKIT_URL }} \
              --env LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }} \
              --env LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}"
              
            pm2 reload voxly-backend --interpreter node -- start server.mjs $ENV_ARGS || { echo "ОШИБКА: Не удалось перезапустить PM2 процесс 'voxly-backend'."; }
            
            echo "Сохранение состояния PM2..."
            pm2 save
