name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Для этого шага не нужно разрешение contents: write, так как мы не пишем в репозиторий.
    # permissions:
    #   contents: write 

    steps:
      - name: 1. Проверка кода (Checkout)
        uses: actions/checkout@v4

      - name: 2. Настройка Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: 3. Получение зависимостей
        run: flutter pub get
        working-directory: ./voxly_frontend

      - name: 4. Сборка Flutter Web (Для корневого пути)
        # Убираем --base-href /Voxly/, так как вы размещаете сайт в корне домена (voxly-audio.ru/)
        run: flutter build web --release
        working-directory: ./voxly_frontend
          
      - name: 5. Развертывание на VPS Selectel по SSH
        uses: appleboy/ssh-action@v1.0.1
        with:
          # Используем секреты, созданные на GitHub
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Команда, которая выполняется на вашем VPS
          script: |
            # 1. Создаем папку для фронтенда, если ее нет
            mkdir -p /var/www/voxly_frontend
            
            # 2. Очищаем старую сборку (важно для чистой установки)
            # ! Очищаем только содержимое, не удаляем саму папку
            find /var/www/voxly_frontend -mindepth 1 -delete
            
            # --- START COPY LOGIC ---
            # Путь к собранным файлам Flutter в runner'е GitHub Actions
            BUILD_SOURCE_PATH="${{ github.workspace }}/voxly_frontend/build/web/"
            # Целевой путь на VPS
            DEPLOY_TARGET_PATH="/var/www/voxly_frontend"
            
            echo "Attempting rsync from: $BUILD_SOURCE_PATH to $DEPLOY_TARGET_PATH"
            
            # 4. Копируем собранные файлы
            # Используем флаг --delete для удаления старых файлов, которых нет в новой сборке.
            # Копируем содержимое $BUILD_SOURCE_PATH в $DEPLOY_TARGET_PATH
            rsync -avz --delete "$BUILD_SOURCE_PATH" "$DEPLOY_TARGET_PATH"
            
            # 5. Перезапускаем HTTP-сервер только после успешного копирования
            # Используем явную команду pm2 reload.
            # Если pm2 reload не сработает (первый запуск), запускаем pm2 start.
            echo "Restarting http-server..."
            pm2 reload voxly-frontend || pm2 start http-server --name "voxly-frontend" -- "$DEPLOY_TARGET_PATH" -p 8080
            
            # 6. Сохраняем состояние PM2 на всякий случай
            pm2 save
