name: Backend CI/CD (Только бэкенд)

on:
  push:
    branches:
      - main
    paths:
      - 'voxly_backend/**'
      - '.github/workflows/deploy_backend_only.yml'

  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Проверка кода (Checkout)
        uses: actions/checkout@v4

      # --- ШАГ 2: Принудительная очистка целевой папки ---
      - name: 2. Принудительная очистка целевой папки на VPS
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            BACKEND_TARGET_DIR="/root/voxly-backend"
            echo "Очистка содержимого папки $BACKEND_TARGET_DIR перед копированием..."
            # Удаляем все внутри папки, включая скрытые файлы (кроме .env, если он не в репозитории)
            rm -rf "$BACKEND_TARGET_DIR"/*
            rm -rf "$BACKEND_TARGET_DIR"/.* || true

      # --- ШАГ 3. КОПИРОВАНИЕ ФАЙЛОВ НА VPS через SCP ---
      # Копируется ./voxly_backend в /root/voxly-backend, создавая вложенную папку.
      - name: 3. Копирование файлов БЭКЕНДА на VPS (/root/voxly-backend)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./voxly_backend"
          target: "/root/voxly-backend"
          overwrite: true
          
      # --- ШАГ 4: УСТАНОВКА и ПЕРЕЗАПУСК БЭКЕНДА (SSH команды) ---
      - name: 4. Установка зависимостей и перезапуск на VPS
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            BACKEND_TARGET_DIR="/root/voxly-backend"
            
            echo "Развертывание БЭКЕНДА в $BACKEND_TARGET_DIR..."
            
            # 1. Перемещение содержимого из вложенной папки на уровень выше
            echo "Перемещение файлов из вложенной папки..."
            # Копируем содержимое voxly_backend/* в текущую папку
            mv "$BACKEND_TARGET_DIR/voxly_backend/"* "$BACKEND_TARGET_DIR"
            # Перемещаем скрытые файлы (например, .gitignore)
            mv "$BACKEND_TARGET_DIR/voxly_backend/".* "$BACKEND_TARGET_DIR" || true
            # Удаляем теперь пустую вложенную папку
            rm -rf "$BACKEND_TARGET_DIR/voxly_backend"

            # 2. Переходим в целевую папку
            cd "$BACKEND_TARGET_DIR" || { echo "ОШИБКА: Не удалось перейти в $BACKEND_TARGET_DIR. Проверьте путь и права."; exit 1; }

            # 3. Установка зависимостей Node.js
            echo "Установка зависимостей Node.js..."
            npm install
            
            # 4. Формирование аргументов ENV (обязательно в одну строку)
            ENV_ARGS="--env PORT=${{ secrets.PORT }} \
              --env REDIS_URL=${{ secrets.REDIS_URL }} \
              --env OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
              --env LIVEKIT_URL=${{ secrets.LIVEKIT_URL }} \
              --env LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }} \
              --env LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}"
              
            # 5. ПЕРЕЗАПУСК PM2 (ИСПРАВЛЕНО): 
            # 'pm2 start' с --force и --update-env гарантирует обновление ENV и перезапуск
            echo "Перезапуск 'server' с обновлением ENV..."
            pm2 start server.mjs --name server --update-env --force $ENV_ARGS || { echo "ОШИБКА: Не удалось запустить/перезапустить PM2 процесс 'server'."; exit 1; }
            
            # 6. Сохранение состояния PM2
            echo "Сохранение состояния PM2..."
            pm2 save
