name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter (beta)
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Clean
        working-directory: ./voxly_frontend
        run: flutter clean

      - name: Install dependencies
        working-directory: ./voxly_frontend
        run: flutter pub get

      - name: Build Flutter web
        working-directory: ./voxly_frontend
        run: flutter build web --release

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: voxly_frontend/build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web_build
          path: build

      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"

      - name: Deploy to server
        run: |
          rsync -e "ssh -p 22 -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" \
          --archive --compress --delete \
          build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/voxly_frontend

      - name: Reload Caddy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl reload caddy
