name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Проверка кода (Checkout)
        uses: actions/checkout@v4

      - name: 2. Настройка Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 3. Получение зависимостей
        run: flutter pub get
        working-directory: ./voxly_frontend

      - name: 4. Сборка Flutter Web
        run: |
            flutter build web --release --base-href /voxly_frontend/
        working-directory: ./voxly_frontend
          
      - name: 5. Развертывание на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./voxly_frontend/build/web
          publish_branch: gh-pages
