name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Проверка кода (Checkout)
        uses: actions/checkout@v4

      - name: 2. Настройка Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: 3. Получение зависимостей
        # Запускаем pub get в папке проекта Flutter
        run: flutter pub get
        working-directory: ./voxly_frontend

      - name: 4. Сборка Flutter Web
        # Папка build/web будет создана внутри voxly_frontend.
        run: flutter build web --release
        working-directory: ./voxly_frontend
          
      # --- НОВЫЙ ШАГ ДЛЯ ИСПРАВЛЕНИЯ ПУТИ RSYNC ---
      - name: 5. Перенос собранных файлов в корень
        # Копируем содержимое собранной папки в папку `web_deploy` в корневом каталоге
        run: |
          mkdir -p web_deploy
          cp -r ./voxly_frontend/build/web/* ./web_deploy/
          echo "Проверка содержимого папки для деплоя:"
          ls -al web_deploy/
        # --- КОНЕЦ НОВОГО ШАГА ---
        
      - name: 6. Развертывание на VPS Selectel по SSH
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Команда, которая выполняется на вашем VPS
          script: |
            # 1. Создаем папку для фронтенда, если ее нет, и гарантируем, что пользователь имеет права на запись
            DEPLOY_TARGET_DIR="/var/www/voxly_frontend"
            mkdir -p "$DEPLOY_TARGET_DIR"
            # Убеждаемся, что текущий SSH-пользователь (например, root) владеет папкой
            chown -R $(whoami):$(whoami) "$DEPLOY_TARGET_DIR"
            
            # 2. Очищаем старую сборку (важно для чистой установки)
            find "$DEPLOY_TARGET_DIR" -mindepth 1 -delete
            
            # --- START COPY LOGIC ---
            # ИСХОДНЫЙ ПУТЬ: Теперь он простой и гарантированно существует
            BUILD_SOURCE_DIR="${{ github.workspace }}/web_deploy"
            # Целевой путь на VPS
            
            # ДИАГНОСТИКА: Убедимся, что файлы существуют перед rsync
            echo "--- Diagnostics ---"
            echo "Listing files in source directory: $BUILD_SOURCE_DIR"
            ls -al "$BUILD_SOURCE_DIR"
            echo "-------------------"
            
            # 4. Копируем собранные файлы
            # Копируем СОДЕРЖИМОЕ папки web_deploy в целевую папку.
            rsync -avz --delete "$BUILD_SOURCE_DIR"/ "$DEPLOY_TARGET_DIR"
            
            # 5. Перезапускаем HTTP-сервер только после успешного копирования
            echo "Restarting http-server..."
            pm2 reload voxly-frontend || pm2 start http-server --name "voxly-frontend" -- "$DEPLOY_TARGET_DIR" -p 8080
            
            # 6. Сохраняем состояние PM2 на всякий случай
            pm2 save
